INSERT INTO Modalidade (nome) VALUES ('Salto em Comprimento');
INSERT INTO Modalidade (nome) VALUES ('Salto em Altura');
INSERT INTO Modalidade (nome) VALUES ('Estafetas');
INSERT INTO Modalidade (nome) VALUES ('Sprint 60m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 100m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 200m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 400m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 60m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 100m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 400m');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Peso');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Martelo');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Dardo');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Disco');
INSERT INTO Modalidade (nome) VALUES ('Maratona');
INSERT INTO Profissional (nome) VALUES ('Laurindo');
INSERT INTO Profissional (nome) VALUES ('Wesley');
INSERT INTO Profissional (nome) VALUES ('Constantino');
INSERT INTO Profissional (nome) VALUES ('Telmo');
INSERT INTO Profissional (nome) VALUES ('Apani');
INSERT INTO Profissional (nome) VALUES ('Anastácia');
INSERT INTO Profissional (nome) VALUES ('Marieta');
INSERT INTO Profissional (nome) VALUES ('Brian');
INSERT INTO Profissional (nome) VALUES ('Alesia');
INSERT INTO Profissional (nome) VALUES ('Gilsa');
INSERT INTO Profissional (nome) VALUES ('Mutaro');
INSERT INTO Profissional (nome) VALUES ('Jon');
INSERT INTO Profissional (nome) VALUES ('Shariya');
INSERT INTO Profissional (nome) VALUES ('Raina');
INSERT INTO Profissional (nome) VALUES ('Henzo');
INSERT INTO Profissional (nome) VALUES ('Valentyn');
INSERT INTO Profissional (nome) VALUES ('Vitor');
INSERT INTO Profissional (nome) VALUES ('Thayssa');
INSERT INTO Profissional (nome) VALUES ('Camilla');
INSERT INTO Profissional (nome) VALUES ('Amritjot');
INSERT INTO Profissional (nome) VALUES ('Célio');
INSERT INTO Profissional (nome) VALUES ('Eduard');
INSERT INTO Profissional (nome) VALUES ('Cinara');
INSERT INTO Profissional (nome) VALUES ('Jussara');
INSERT INTO Profissional (nome) VALUES ('Taís');
INSERT INTO Profissional (nome) VALUES ('Rita');
INSERT INTO Profissional (nome) VALUES ('Malú');
INSERT INTO Profissional (nome) VALUES ('Ribana');
INSERT INTO Profissional (nome) VALUES ('Mladen');
INSERT INTO Profissional (nome) VALUES ('Neyton');
INSERT INTO Profissional (nome) VALUES ('Sílvia');
INSERT INTO Profissional (nome) VALUES ('Hélio');
INSERT INTO Profissional (nome) VALUES ('Kentia');
INSERT INTO Profissional (nome) VALUES ('Óscar');
INSERT INTO Profissional (nome) VALUES ('Kianna');
INSERT INTO Profissional (nome) VALUES ('Jennifer');
INSERT INTO Profissional (nome) VALUES ('Carlene');
INSERT INTO Profissional (nome) VALUES ('Theo');
INSERT INTO Profissional (nome) VALUES ('Dérick');
INSERT INTO Profissional (nome) VALUES ('Tarciso');
INSERT INTO Profissional (nome) VALUES ('Giulhia');
INSERT INTO Profissional (nome) VALUES ('Olivia');
INSERT INTO Profissional (nome) VALUES ('Miranda');
INSERT INTO Profissional (nome) VALUES ('Teodora');
INSERT INTO Profissional (nome) VALUES ('Derick');
INSERT INTO Profissional (nome) VALUES ('Keyla');
INSERT INTO Profissional (nome) VALUES ('Núbia');
INSERT INTO Profissional (nome) VALUES ('Zi');
INSERT INTO Profissional (nome) VALUES ('Mabel');
INSERT INTO Profissional (nome) VALUES ('Harjot');
INSERT INTO Profissional (nome) VALUES ('Arnaldo');
INSERT INTO Profissional (nome) VALUES ('Issa');
INSERT INTO Profissional (nome) VALUES ('Miguela');
INSERT INTO Profissional (nome) VALUES ('Liany');
INSERT INTO Profissional (nome) VALUES ('Ava');
INSERT INTO Profissional (nome) VALUES ('Gurvir');
INSERT INTO Profissional (nome) VALUES ('Ibrahim');
INSERT INTO Profissional (nome) VALUES ('Zoé');
INSERT INTO Profissional (nome) VALUES ('Gulmira');
INSERT INTO Profissional (nome) VALUES ('Felipe');
INSERT INTO Profissional (nome) VALUES ('Daphne');
INSERT INTO Profissional (nome) VALUES ('Rasan');
INSERT INTO Profissional (nome) VALUES ('Lourenço');
INSERT INTO Profissional (nome) VALUES ('Alexia');
INSERT INTO Profissional (nome) VALUES ('Letícia');
INSERT INTO Profissional (nome) VALUES ('Melvyn');
INSERT INTO Profissional (nome) VALUES ('Anurroi');
INSERT INTO Profissional (nome) VALUES ('Évelyn');
INSERT INTO Profissional (nome) VALUES ('Dileison');
INSERT INTO Profissional (nome) VALUES ('Bryan');
INSERT INTO Profissional (nome) VALUES ('Anaísa');
INSERT INTO Profissional (nome) VALUES ('Olinda');
INSERT INTO Profissional (nome) VALUES ('Ygor');
INSERT INTO Profissional (nome) VALUES ('Ian');
INSERT INTO Profissional (nome) VALUES ('Nahyma');
INSERT INTO Profissional (nome) VALUES ('Martins');
INSERT INTO Profissional (nome) VALUES ('Lorenza');
INSERT INTO Profissional (nome) VALUES ('Iana');
INSERT INTO Profissional (nome) VALUES ('Murodjon');
INSERT INTO Profissional (nome) VALUES ('Rayssa');
INSERT INTO Profissional (nome) VALUES ('Filipe');
INSERT INTO Profissional (nome) VALUES ('Lamarana');
INSERT INTO Profissional (nome) VALUES ('Diamantino');
INSERT INTO Profissional (nome) VALUES ('Abrish');
INSERT INTO Profissional (nome) VALUES ('Ivory');
INSERT INTO Profissional (nome) VALUES ('Idjatu');
INSERT INTO Profissional (nome) VALUES ('Henry');
INSERT INTO Profissional (nome) VALUES ('Khadija');
INSERT INTO Profissional (nome) VALUES ('Cassandra');
INSERT INTO Profissional (nome) VALUES ('Naila');
INSERT INTO Profissional (nome) VALUES ('Rajina');
INSERT INTO Profissional (nome) VALUES ('Cinthia');
INSERT INTO Profissional (nome) VALUES ('Ruth');
INSERT INTO Profissional (nome) VALUES ('Spencer');
INSERT INTO Profissional (nome) VALUES ('Chloe');
INSERT INTO Profissional (nome) VALUES ('Papa-Ndiogou');
INSERT INTO Profissional (nome) VALUES ('Erik');
INSERT INTO Profissional (nome) VALUES ('Tércio');
INSERT INTO Profissional (nome) VALUES ('Cheila');
INSERT INTO Profissional (nome) VALUES ('Leandro');
INSERT INTO Profissional (nome) VALUES ('Sohany');
INSERT INTO Profissional (nome) VALUES ('Elaina');
INSERT INTO Profissional (nome) VALUES ('Helen');
INSERT INTO Profissional (nome) VALUES ('Mattia');
INSERT INTO Profissional (nome) VALUES ('Nirbhay');
INSERT INTO Profissional (nome) VALUES ('Eurico');
INSERT INTO Profissional (nome) VALUES ('Savannah');
INSERT INTO Profissional (nome) VALUES ('Welnir');
INSERT INTO Profissional (nome) VALUES ('Ayla');
INSERT INTO Profissional (nome) VALUES ('Didier');
INSERT INTO Profissional (nome) VALUES ('Gláucio');
INSERT INTO Profissional (nome) VALUES ('Teodoro');
INSERT INTO Profissional (nome) VALUES ('Kyllen');
INSERT INTO Profissional (nome) VALUES ('Raul');
INSERT INTO Profissional (nome) VALUES ('Melissa');
INSERT INTO Profissional (nome) VALUES ('Macar');
INSERT INTO Profissional (nome) VALUES ('Cassiano');
INSERT INTO Profissional (nome) VALUES ('Aarya');
INSERT INTO Profissional (nome) VALUES ('Tom');
INSERT INTO Profissional (nome) VALUES ('Edir');
INSERT INTO Profissional (nome) VALUES ('Marius');
INSERT INTO Profissional (nome) VALUES ('Hélida');
INSERT INTO Profissional (nome) VALUES ('Hawa');
INSERT INTO Profissional (nome) VALUES ('Nélio');
INSERT INTO Profissional (nome) VALUES ('Joseline');
INSERT INTO Profissional (nome) VALUES ('Flint');
INSERT INTO Profissional (nome) VALUES ('Anair');
INSERT INTO Profissional (nome) VALUES ('Kauana');
INSERT INTO Profissional (nome) VALUES ('Manish');
INSERT INTO Profissional (nome) VALUES ('Adriane');
INSERT INTO Profissional (nome) VALUES ('Bibek');
INSERT INTO Profissional (nome) VALUES ('Flor');
INSERT INTO Profissional (nome) VALUES ('Vinildo');
INSERT INTO Profissional (nome) VALUES ('Naksh');
INSERT INTO Profissional (nome) VALUES ('Boqian');
INSERT INTO Profissional (nome) VALUES ('Julciane');
INSERT INTO Profissional (nome) VALUES ('Muntaha');
INSERT INTO Profissional (nome) VALUES ('Humaira');
INSERT INTO Profissional (nome) VALUES ('Giacomo');
INSERT INTO Profissional (nome) VALUES ('Rosinda');
INSERT INTO Profissional (nome) VALUES ('Nair');
INSERT INTO Profissional (nome) VALUES ('Viviana');
INSERT INTO Profissional (nome) VALUES ('Cátia');
INSERT INTO Profissional (nome) VALUES ('Ndiack');
INSERT INTO Profissional (nome) VALUES ('Harsh');
INSERT INTO Profissional (nome) VALUES ('Martino');
INSERT INTO Profissional (nome) VALUES ('Amaia');
INSERT INTO Profissional (nome) VALUES ('Rayna');
INSERT INTO Profissional (nome) VALUES ('Ionut');
INSERT INTO Profissional (nome) VALUES ('Rafia');
INSERT INTO Profissional (nome) VALUES ('Kevin-Cosmin');
INSERT INTO Profissional (nome) VALUES ('Humberto');
INSERT INTO Profissional (nome) VALUES ('Neria');
INSERT INTO Profissional (nome) VALUES ('Ming');
INSERT INTO Profissional (nome) VALUES ('Flávia');
INSERT INTO Profissional (nome) VALUES ('Nelson');
INSERT INTO Profissional (nome) VALUES ('Jamie');
INSERT INTO Profissional (nome) VALUES ('Vania');
INSERT INTO Profissional (nome) VALUES ('Liana');
INSERT INTO Profissional (nome) VALUES ('Oziel');
INSERT INTO Profissional (nome) VALUES ('Zehan');
INSERT INTO Profissional (nome) VALUES ('Solomiia');
INSERT INTO Profissional (nome) VALUES ('Ellen');
INSERT INTO Profissional (nome) VALUES ('June');
INSERT INTO Profissional (nome) VALUES ('Anastacia');
INSERT INTO Profissional (nome) VALUES ('Emilly');
INSERT INTO Profissional (nome) VALUES ('Mykail');
INSERT INTO Profissional (nome) VALUES ('Aiden');
INSERT INTO Profissional (nome) VALUES ('Marya');
INSERT INTO Profissional (nome) VALUES ('Maura');
INSERT INTO Profissional (nome) VALUES ('Claúdio');
INSERT INTO Profissional (nome) VALUES ('River');
INSERT INTO Profissional (nome) VALUES ('Manteg');
INSERT INTO Profissional (nome) VALUES ('Bidushi');
INSERT INTO Profissional (nome) VALUES ('Fernanda');
INSERT INTO Profissional (nome) VALUES ('Isak');
INSERT INTO Profissional (nome) VALUES ('Kailany');
INSERT INTO Profissional (nome) VALUES ('Angélica');
INSERT INTO Profissional (nome) VALUES ('Stella');
INSERT INTO Profissional (nome) VALUES ('Élson');
INSERT INTO Profissional (nome) VALUES ('Ali');
INSERT INTO Profissional (nome) VALUES ('Josué');
INSERT INTO Profissional (nome) VALUES ('Kiluanji');
INSERT INTO Profissional (nome) VALUES ('Nayra');
INSERT INTO Profissional (nome) VALUES ('Yellen');
INSERT INTO Profissional (nome) VALUES ('Manjot');
INSERT INTO Profissional (nome) VALUES ('Fortunato');
INSERT INTO Profissional (nome) VALUES ('Laysla');
INSERT INTO Profissional (nome) VALUES ('Asael');
INSERT INTO Profissional (nome) VALUES ('Djariato');
INSERT INTO Profissional (nome) VALUES ('Smahir');
INSERT INTO Profissional (nome) VALUES ('Aarnav');
INSERT INTO Profissional (nome) VALUES ('Jaycee');
INSERT INTO Profissional (nome) VALUES ('Adame');
INSERT INTO Profissional (nome) VALUES ('Emma');
INSERT INTO Profissional (nome) VALUES ('Ábda');
INSERT INTO Profissional (nome) VALUES ('Éder');
INSERT INTO Profissional (nome) VALUES ('Jacqueline');
INSERT INTO Profissional (nome) VALUES ('Wayiza');
INSERT INTO Profissional (nome) VALUES ('Zahira');
INSERT INTO Profissional (nome) VALUES ('Brahim');
INSERT INTO Profissional (nome) VALUES ('Aleksandr');
INSERT INTO Profissional (nome) VALUES ('Ella');
INSERT INTO Profissional (nome) VALUES ('Victoria');
INSERT INTO Profissional (nome) VALUES ('Lisandra');
INSERT INTO Profissional (nome) VALUES ('Céline');
INSERT INTO Profissional (nome) VALUES ('Jéssica');
INSERT INTO Profissional (nome) VALUES ('Zihao');
INSERT INTO Profissional (nome) VALUES ('Enzo');
INSERT INTO Profissional (nome) VALUES ('Marcelo');
INSERT INTO Profissional (nome) VALUES ('Miroslava');
INSERT INTO Profissional (nome) VALUES ('Élis');
INSERT INTO Profissional (nome) VALUES ('Isys');
INSERT INTO Profissional (nome) VALUES ('Ciyara');
INSERT INTO Profissional (nome) VALUES ('Raissa');
INSERT INTO Profissional (nome) VALUES ('Liz');
INSERT INTO Profissional (nome) VALUES ('Fiona');
INSERT INTO Profissional (nome) VALUES ('Szymon');
INSERT INTO Profissional (nome) VALUES ('Wildy');
INSERT INTO Profissional (nome) VALUES ('Geralda');
INSERT INTO Profissional (nome) VALUES ('Jeremias');
INSERT INTO Profissional (nome) VALUES ('Jessé');
INSERT INTO Profissional (nome) VALUES ('Carmel');
INSERT INTO Profissional (nome) VALUES ('Gaspard');
INSERT INTO Profissional (nome) VALUES ('Samaritana');
INSERT INTO Profissional (nome) VALUES ('Helaine');
INSERT INTO Profissional (nome) VALUES ('Destiny');
INSERT INTO Profissional (nome) VALUES ('Chelsea');
INSERT INTO Profissional (nome) VALUES ('Elián');
INSERT INTO Profissional (nome) VALUES ('Viviane');
INSERT INTO Profissional (nome) VALUES ('Inácio');
INSERT INTO Profissional (nome) VALUES ('Maya');
INSERT INTO Profissional (nome) VALUES ('Suprajeet');
INSERT INTO Profissional (nome) VALUES ('Tino');
INSERT INTO Profissional (nome) VALUES ('Micah');
INSERT INTO Profissional (nome) VALUES ('Hélcia');
INSERT INTO Profissional (nome) VALUES ('Kadirkhan');
INSERT INTO Profissional (nome) VALUES ('Yogyadeep');
INSERT INTO Profissional (nome) VALUES ('Ahnaf');
INSERT INTO Profissional (nome) VALUES ('Jeovana');
INSERT INTO Profissional (nome) VALUES ('Lavonne');
INSERT INTO Profissional (nome) VALUES ('Dierson');
INSERT INTO Profissional (nome) VALUES ('Keyson');
INSERT INTO Profissional (nome) VALUES ('Noecris');
INSERT INTO Profissional (nome) VALUES ('Ânia');
INSERT INTO Profissional (nome) VALUES ('Denis');
INSERT INTO Profissional (nome) VALUES ('Hérmen');
INSERT INTO Profissional (nome) VALUES ('Fabiana');
INSERT INTO Profissional (nome) VALUES ('Ariana');
INSERT INTO Profissional (nome) VALUES ('Jivreet');
INSERT INTO Profissional (nome) VALUES ('Lobo');
INSERT INTO Profissional (nome) VALUES ('Seerat');
INSERT INTO Profissional (nome) VALUES ('Mansirat');
INSERT INTO Profissional (nome) VALUES ('Otchali');
INSERT INTO Profissional (nome) VALUES ('Raíssa');
INSERT INTO Profissional (nome) VALUES ('Minhal');
INSERT INTO Profissional (nome) VALUES ('Elson');
INSERT INTO Profissional (nome) VALUES ('Steven');
INSERT INTO Profissional (nome) VALUES ('Laya');
INSERT INTO Profissional (nome) VALUES ('Melinda');
INSERT INTO Profissional (nome) VALUES ('Nilo');
INSERT INTO Profissional (nome) VALUES ('Harrison');
INSERT INTO Profissional (nome) VALUES ('Emanuelly');
INSERT INTO Profissional (nome) VALUES ('Brianna');
INSERT INTO Profissional (nome) VALUES ('Yudi');
INSERT INTO Profissional (nome) VALUES ('Prudêncio');
INSERT INTO Profissional (nome) VALUES ('Malia');
INSERT INTO Profissional (nome) VALUES ('Stanislawa');
INSERT INTO Profissional (nome) VALUES ('Harsirat');
INSERT INTO Profissional (nome) VALUES ('Niah');
INSERT INTO Profissional (nome) VALUES ('Florinda');
INSERT INTO Profissional (nome) VALUES ('Dinora');
INSERT INTO Profissional (nome) VALUES ('Natasha');
INSERT INTO Profissional (nome) VALUES ('Luinysa');
INSERT INTO Profissional (nome) VALUES ('Vida');
INSERT INTO Profissional (nome) VALUES ('Jessie');
INSERT INTO Profissional (nome) VALUES ('Bianca');
INSERT INTO Profissional (nome) VALUES ('Evilly');
INSERT INTO Profissional (nome) VALUES ('Noelle');
INSERT INTO Profissional (nome) VALUES ('Palmira');
INSERT INTO Profissional (nome) VALUES ('Aida');
INSERT INTO Profissional (nome) VALUES ('Josemar');
INSERT INTO Profissional (nome) VALUES ('Marlon');
INSERT INTO Profissional (nome) VALUES ('Mágui');
INSERT INTO Profissional (nome) VALUES ('Aryana');
INSERT INTO Profissional (nome) VALUES ('Patrício');
INSERT INTO Profissional (nome) VALUES ('Daércio');
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Rodrigo Tiago Oliveira Ferreira', '123', '199', 'Priscos, Braga', '1976-5-31', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Márcia Filipa Vilela Oliveira Teixeira', '121', '154', 'Pedralva, Braga', '1984-8-12', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Miguel da Silva Pereira', '77', '177', 'Sequeira, Braga', '1979-5-5', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Amorim de Beir', '130', '221', 'Lomar e Arcos, Braga', '1992-12-26', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'José Nuno Martins da Costa', '102', '196', 'Mire de Tibães, Braga', '1978-12-3', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Daniel José Travessa Pereira', '115', '210', 'São Vicente, Braga', '1992-2-12', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Paulo Jorge da Silva Araújo', '83', '215', 'Gualtar, Braga', '1992-8-15', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipa Alves dos Santos', '87', '177', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1992-1-3', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Carlos Pereira Rodrigues', '106', '194', 'Adaúfe, Braga', '1994-8-27', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Alberto Rui Vilaverde Monteiro da Silva', '93', '187', 'Lamas, Braga', '1985-12-28', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Fernandes de Lima', '116', '182', 'Vilaça e Fradelos, Braga', '1982-4-26', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Sara Maria Barreira Melo', '103', '231', 'Celeirós, Aveleda e Vimieiro, Braga', '1977-6-29', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tiago Manuel Queirós Barata', '121', '202', 'Crespos e Pousada, Braga', '1984-9-10', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Lázaro Donato Martins Pinheiro', '78', '205', 'Tebosa, Braga', '1985-9-7', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Manuel Silva Antunes', '115', '181', 'Ruilhe, Braga', '1977-10-26', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Rafael Olim Martins', '116', '200', 'Vilaça e Fradelos, Braga', '1982-5-6', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Carlos de Amorim Figueiredo', '102', '194', 'Braga (Maximinos, Sé e Cividade), Braga', '1994-11-9', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Lucas Leite Chaves Quintela', '94', '182', 'Celeirós, Aveleda e Vimieiro, Braga', '1979-3-30', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Tiago Oliveira Sousa Nogueira Lopes', '46', '196', 'Tadim, Braga', '1987-12-17', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Diogo Mendes Teixeira da Mota', '80', '161', 'Gualtar, Braga', '1993-7-19', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Nuno Filipe Maranhao dos Reis', '120', '221', 'São Victor, Braga', '1995-12-30', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Hugo André da Silva Veloso Moreira', '121', '179', 'Celeirós, Aveleda e Vimieiro, Braga', '1985-10-4', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Nélson Ramos Alves', '101', '180', 'Figueiredo, Braga', '1982-1-24', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Gabriela Sá Martins', '103', '231', 'Guisande e Oliveira (São Pedro), Braga', '1986-3-11', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ilda Raquel Durães Pinto', '105', '180', 'Crespos e Pousada, Braga', '1979-12-8', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Pedro da Cunha Monteiro', '92', '186', 'Arentim e Cunha, Braga', '1978-11-7', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Nuno Borges Cruz Oliveira', '102', '203', 'Pedralva, Braga', '1977-6-27', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Filipe Carvalho Barbosa', '116', '219', 'Arentim e Cunha, Braga', '1981-3-23', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Pedro Miguel da Rocha Ribeiro', '95', '201', 'Gualtar, Braga', '1976-11-1', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Fábio Fernandes Silva', '75', '236', 'Crespos e Pousada, Braga', '1983-2-8', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'António Manuel Carvalho Gonçalves', '119', '205', 'Nogueiró e Tenões, Braga', '1988-3-2', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Diogo Filipe Ferreira Pereira Monteiro', '81', '187', 'Braga (Maximinos, Sé e Cividade), Braga', '1994-2-23', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Paulo da Costa Pereira', '126', '212', 'Lomar e Arcos, Braga', '1986-12-16', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Nuno Cardoso Gonçalves de Abreu', '118', '175', 'Gualtar, Braga', '1976-11-6', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Filipe Dantas Costa', '137', '203', 'Nogueira, Fraião e Lamaçães, Braga', '1991-5-4', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Rafael Antunes Simões', '74', '220', 'Ferreiros e Gondizalves, Braga', '1975-8-22', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Eduardo Semanas de Oliveira Araújo', '93', '221', 'Nogueiró e Tenões, Braga', '1987-11-9', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Nuno Fernandes Freitas', '68', '215', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1977-6-24', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Hugo Filipe Duarte Carvalho', '92', '227', 'Espinho, Braga', '1982-8-12', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joel Alexandre Dias Ferreira', '116', '151', 'Nogueiró e Tenões, Braga', '1993-11-28', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Machado da Silva', '86', '188', 'Mire de Tibães, Braga', '1987-12-14', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Daniela Eduarda Cruz Fernandes', '55', '183', 'Adaúfe, Braga', '1994-4-23', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bernardo Maria Cortez Marques Nogueira da Graça', '67', '188', 'Lamas, Braga', '1982-11-15', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Miguel Albuquerque Regueiras', '82', '192', 'Braga (Maximinos, Sé e Cividade), Braga', '1987-12-19', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Angélica Matos de Freitas', '122', '167', 'Este (São Pedro e São Mamede), Braga', '1989-2-9', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Guilherme João Cerqueira da Mota Miranda', '88', '198', 'Ruilhe, Braga', '1991-8-30', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Alexandre Esteves Miranda', '70', '178', 'Braga (Maximinos, Sé e Cividade), Braga', '1990-6-10', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tiago André Castro Rodrigues Sousa', '97', '196', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1988-4-18', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Filipe Costa Machado', '121', '196', 'Espinho, Braga', '1975-7-31', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joana Esteves Dantas', '104', '233', 'Morreira e Trandeiras, Braga', '1975-4-1', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Nuno Brandão Silva', '103', '161', 'Sobreposta, Braga', '1994-2-7', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Manuel Almeida Vieira de Castro', '109', '220', 'Mire de Tibães, Braga', '1983-12-6', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luís Miguel Aquino Silva', '111', '205', 'Pedralva, Braga', '1995-2-1', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Nuno Alexandre Pereira Machado', '135', '221', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1983-3-21', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Melânia Rafaela Sousa Pereira', '99', '212', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1979-5-28', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Mateus Ferreira da Silva', '71', '198', 'Braga (Maximinos, Sé e Cividade), Braga', '1981-11-9', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tiago Esteves Rodrigues', '117', '206', 'Padim da Graça, Braga', '1993-1-28', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Bruna Gonçalves Araújo', '77', '192', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1995-7-12', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Machado Fernandes', '77', '191', 'Gualtar, Braga', '1987-10-10', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Daniel Pereira da Silva', '85', '197', 'Esporões, Braga', '1983-6-11', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Eduardo Luís Vieira Pereira', '108', '200', 'Celeirós, Aveleda e Vimieiro, Braga', '1985-10-2', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Bruno Miguel Faria Fernandes', '133', '186', 'Este (São Pedro e São Mamede), Braga', '1979-10-10', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Bruno Roberto Fernandes Freitas', '131', '208', 'Tebosa, Braga', '1979-5-4', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Helena Poças Martins', '105', '202', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1984-3-28', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Andreia Martins Alves', '131', '175', 'Mire de Tibães, Braga', '1987-6-10', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Miguel Arrepia Ferreira', '121', '208', 'Crespos e Pousada, Braga', '1992-8-16', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Eduardo Jorge Santos Teixeira', '94', '221', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1990-2-23', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ricardo José de Magalhães e Silva', '98', '183', 'Braga (Maximinos, Sé e Cividade), Braga', '1984-6-24', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joana Castro e Sousa', '85', '196', 'Este (São Pedro e São Mamede), Braga', '1995-10-13', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Susana Vitória Sá Silva Marques', '69', '214', 'Cabreiros e Passos (São Julião), Braga', '1977-4-24', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luis Filipe da Silva Costa', '94', '228', 'Palmeira, Braga', '1975-2-13', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Pedro Rafael Martins de Oliveira', '105', '181', 'Ruilhe, Braga', '1990-10-23', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Miguel Lopes Salgado', '99', '206', 'Real, Dume e Semelhe, Braga', '1977-6-8', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Mafalda Colaco Parente Morais da Costa', '106', '238', 'Real, Dume e Semelhe, Braga', '1981-6-4', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Gonçalves Correia', '145', '174', 'Sobreposta, Braga', '1989-11-7', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Gonçalo Nuno Fernandes e Ferreira', '91', '192', 'Pedralva, Braga', '1983-4-21', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Maria Francisca Tavares Martins Fernandes', '105', '220', 'Esporões, Braga', '1978-4-15', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luísa Maria Carvalho Fernandes', '110', '197', 'Tadim, Braga', '1979-2-20', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Loureiro da Silva', '138', '189', 'Vilaça e Fradelos, Braga', '1987-11-22', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Duarte Vila Verde Silva', '98', '180', 'Morreira e Trandeiras, Braga', '1990-8-21', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Maria Luísa Faria Silva', '87', '189', 'Tadim, Braga', '1994-4-1', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Bernardo Coelho Nunes', '113', '194', 'Morreira e Trandeiras, Braga', '1976-9-5', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Bruno Miguel Fernandes Teixeira', '116', '178', 'Esporões, Braga', '1987-10-10', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ângelo André Castro de Sousa', '82', '163', 'Cabreiros e Passos (São Julião), Braga', '1977-9-28', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miguel Moreira Montenegro da Silva', '92', '203', 'Cabreiros e Passos (São Julião), Braga', '1982-3-2', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Dias Fernandes', '79', '215', 'Ruilhe, Braga', '1985-3-26', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Artur Bernardo da Silva Ribeiro', '83', '226', 'Padim da Graça, Braga', '1991-7-29', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Daniel Martins Carvalho Ferreira', '97', '197', 'Vilaça e Fradelos, Braga', '1977-11-26', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Pedro Neto Reis', '118', '190', 'Real, Dume e Semelhe, Braga', '1981-5-18', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Moisés Araújo Antunes', '93', '214', 'São Vicente, Braga', '1987-10-19', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ivo Dantas Pimenta', '133', '180', 'Adaúfe, Braga', '1980-5-17', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Henrique Vilares Gomes', '86', '208', 'Nogueira, Fraião e Lamaçães, Braga', '1977-8-28', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luis Filipe de Carvalho Bigas Arruda Ribeiro', '105', '185', 'Priscos, Braga', '1987-7-2', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Manuel Loureiro Vieira', '77', '198', 'Lamas, Braga', '1984-12-27', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Shahzod Yusupov', '68', '171', 'Braga (Maximinos, Sé e Cividade), Braga', '1990-7-5', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Angélica Soares Cunha', '131', '216', 'Esporões, Braga', '1986-7-2', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria José Borges Pires', '77', '198', 'Palmeira, Braga', '1989-1-4', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Paulo Silva Ferreira', '119', '242', 'Arentim e Cunha, Braga', '1976-10-20', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Gonçalo Pinto Nogueira', '99', '194', 'Crespos e Pousada, Braga', '1992-11-12', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Manuel Pires Rodrigues', '108', '159', 'São Victor, Braga', '1978-1-20', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Alexandre Jose Branco Ferreira', '71', '193', 'Nogueira, Fraião e Lamaçães, Braga', '1995-2-22', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Pedro Agostinho de Carvalho Henriques', '111', '184', 'Espinho, Braga', '1987-5-30', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo André Coelho Cardoso', '94', '228', 'Sobreposta, Braga', '1981-1-26', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipe José da Silva Freitas', '73', '157', 'Padim da Graça, Braga', '1981-8-12', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Tiago Gabriel Pereira da Silva', '98', '214', 'Braga (Maximinos, Sé e Cividade), Braga', '1976-8-9', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Queiros Gomes', '81', '221', 'Sobreposta, Braga', '1993-10-29', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ana Patrícia Silva Faria', '104', '200', 'Celeirós, Aveleda e Vimieiro, Braga', '1995-9-23', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Aniceto Rodrigues Rocha', '79', '188', 'Sequeira, Braga', '1984-2-5', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Inês de Azevedo Mouroa Alves', '106', '196', 'Celeirós, Aveleda e Vimieiro, Braga', '1978-7-3', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Simão Pedro Santa Cruz Oliveira', '96', '223', 'Esporões, Braga', '1975-8-14', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Sousa Figueiredo', '109', '190', 'Arentim e Cunha, Braga', '1990-6-24', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Manuel Gonçalves de Oliveira', '112', '180', 'Nogueiró e Tenões, Braga', '1977-2-12', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo Manuel Cunha', '107', '193', 'Nogueiró e Tenões, Braga', '1986-3-1', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo André Silva Pereira', '100', '167', 'Padim da Graça, Braga', '1977-10-29', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Varandas de Melo Barros', '90', '212', 'Adaúfe, Braga', '1981-11-22', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Gonçalo dos Santos Pires Pinheiro', '78', '199', 'Adaúfe, Braga', '1984-6-23', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Paulo Lopes de Vasconcelos', '89', '201', 'Esporões, Braga', '1980-8-4', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luís Pedro da Silva Vila', '96', '185', 'Lomar e Arcos, Braga', '1979-1-31', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Jorge Gabriel Alves Cerqueira', '90', '228', 'Nogueira, Fraião e Lamaçães, Braga', '1990-5-10', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Pedro Araújo Parente', '107', '225', 'Ferreiros e Gondizalves, Braga', '1993-2-4', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tomás Salazar Valente', '82', '201', 'Este (São Pedro e São Mamede), Braga', '1987-3-31', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Paulo César Ribeirinho Henriques', '82', '188', 'Morreira e Trandeiras, Braga', '1991-4-8', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Miguel Alves Rocha', '114', '183', 'Merelim (São Pedro) e Frossos, Braga', '1986-7-22', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Filipe Traila de Sousa', '120', '218', 'Arentim e Cunha, Braga', '1987-2-23', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'José Carlos Leite Magalhães', '124', '210', 'Priscos, Braga', '1984-9-14', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Araújo Costa', '100', '198', 'Real, Dume e Semelhe, Braga', '1984-11-12', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Manuel da Silva Queirós', '93', '208', 'Ruilhe, Braga', '1995-6-21', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'José Ricardo Sousa Mendes da Cunha', '153', '192', 'Palmeira, Braga', '1988-1-14', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Goncalo Nuno Esperança Quesado', '78', '162', 'Ruilhe, Braga', '1981-6-10', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Carlos Manuel Marques Afonso', '92', '201', 'Ferreiros e Gondizalves, Braga', '1978-5-4', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'José Miguel Fernandes Madeira Pinto', '147', '197', 'Ruilhe, Braga', '1987-3-25', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipe Barbosa Soares da Costa', '108', '214', 'Ferreiros e Gondizalves, Braga', '1982-8-11', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Paulo Fontes Delgado', '83', '215', 'Nogueiró e Tenões, Braga', '1989-11-21', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tomás Francisco Cruz Costa', '113', '181', 'Gualtar, Braga', '1984-1-27', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Diogo Xavier Monteiro', '81', '141', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1975-4-10', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Pedro Amorim Gomes', '135', '193', 'Tadim, Braga', '1994-3-14', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Filipe de Sousa Matos Ferreira', '107', '192', 'Celeirós, Aveleda e Vimieiro, Braga', '1990-4-18', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Diogo Vicente Magalhaes Vilela Silva', '89', '190', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1995-1-4', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Manuel António Marinho Marques', '128', '216', 'Adaúfe, Braga', '1983-7-17', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Paulo Jorge Moreira Lima', '93', '180', 'Ruilhe, Braga', '1978-12-9', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Pedro Dias Parente', '84', '161', 'Figueiredo, Braga', '1994-2-2', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipe da Cunha Faria Gajo', '114', '222', 'Mire de Tibães, Braga', '1992-6-4', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Gonçalo José Azevedo Esteves', '81', '194', 'Este (São Pedro e São Mamede), Braga', '1977-7-28', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Luísa Pereira de César', '108', '202', 'Sobreposta, Braga', '1979-10-17', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Eduardo Lourenço da Conceição', '90', '193', 'Tadim, Braga', '1978-7-31', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joaquim Francisco Barata Simões', '143', '215', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1984-8-12', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joana Isabel Albuquerque Silva Matos', '105', '226', 'Este (São Pedro e São Mamede), Braga', '1978-12-4', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ricardo José Santos Veloso', '89', '189', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1979-9-22', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Alexandre Reis da Costa', '105', '243', 'São Vicente, Braga', '1988-4-16', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Gonçalo Leal da Mota Meireles Moreira', '106', '168', 'São Victor, Braga', '1995-1-15', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Francisco Teixeira Bastos da Mota', '110', '152', 'São Victor, Braga', '1976-10-7', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ulisses Tiago Simões Araújo', '109', '223', 'São Vicente, Braga', '1987-1-28', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Miguel Pimenta e Cunha', '112', '198', 'Celeirós, Aveleda e Vimieiro, Braga', '1987-1-12', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Mário Rui Freitas Coelho', '89', '197', 'Adaúfe, Braga', '1983-11-23', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ana Beatriz Castro Afonso', '91', '176', 'Esporões, Braga', '1993-5-7', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Duarte Manuel Vilar de Oliveira', '82', '186', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1985-7-6', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luís Alberto Diogo Pereira de Lima', '55', '211', 'Real, Dume e Semelhe, Braga', '1979-8-30', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Simão Lemos Silva', '98', '195', 'Sobreposta, Braga', '1985-3-7', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Bernardo Coutinho Barreiros de Freitas', '134', '190', 'Ruilhe, Braga', '1986-7-14', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Renato Jorge Cruzinha da Silva', '118', '186', 'Palmeira, Braga', '1982-4-15', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bernardo José Barbosa Alves', '127', '218', 'Palmeira, Braga', '1976-4-21', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruna Francisca Capela Alvarães', '85', '198', 'Padim da Graça, Braga', '1976-12-21', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Filipe Moreira Mendes', '126', '239', 'Guisande e Oliveira (São Pedro), Braga', '1994-5-20', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Gonçalo Rodrigues Pinto', '124', '199', 'Nogueiró e Tenões, Braga', '1988-8-2', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Pedro Magalhães Teixeira', '90', '188', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1990-5-23', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Tiago Machado Braga', '88', '191', 'Nogueira, Fraião e Lamaçães, Braga', '1983-1-2', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Marco Alexandre Félix de Lima', '101', '202', 'Nogueiró e Tenões, Braga', '1975-5-21', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miriam Miranda Pinto', '88', '220', 'Cabreiros e Passos (São Julião), Braga', '1988-11-8', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Rúben de Castro Rodrigues', '88', '188', 'Tebosa, Braga', '1982-8-7', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Beatriz Freitas Rocha', '115', '236', 'Celeirós, Aveleda e Vimieiro, Braga', '1985-6-18', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Pedro Pereira Sampaio', '109', '227', 'Lomar e Arcos, Braga', '1975-9-2', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Margarida Alves Faria', '126', '200', 'Celeirós, Aveleda e Vimieiro, Braga', '1981-9-12', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Santos Arezes Costa', '104', '209', 'Lomar e Arcos, Braga', '1984-5-17', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ricardo Nuno de Castro Cruz', '86', '176', 'Lomar e Arcos, Braga', '1990-6-28', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Paulo Freitas da Cunha', '92', '194', 'Braga (Maximinos, Sé e Cividade), Braga', '1984-9-3', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Áureo Joel Costa dos Santos Benedito', '119', '169', 'São Victor, Braga', '1989-1-30', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipe Miguel Teixeira Freitas Guimaraes', '57', '188', 'São Victor, Braga', '1989-8-4', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Gomes Machado Monteiro Fernandes', '103', '192', 'Lamas, Braga', '1978-3-14', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Filipe Emanuel Santos Fernandes', '88', '180', 'Ruilhe, Braga', '1994-2-27', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Miguel Raposo Fonseca', '86', '170', 'Braga (Maximinos, Sé e Cividade), Braga', '1980-4-16', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Daniel Assuncao Regado', '126', '224', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1986-6-14', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipa Barbosa Ferraz Silva', '85', '203', 'Tadim, Braga', '1981-12-10', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'David António Vieira dos Santos Moura Neto', '91', '201', 'Sequeira, Braga', '1994-8-18', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ricardo Jorge Silva Ferreira', '105', '198', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1982-1-4', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rodrigo da Silva Pimentel', '97', '219', 'Ferreiros e Gondizalves, Braga', '1988-4-7', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Catarina Freitas da Cruz', '109', '180', 'Tadim, Braga', '1991-7-28', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Alves Martins Carvalho', '120', '189', 'Palmeira, Braga', '1995-5-4', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Emanuel Silva Rodrigues', '106', '216', 'Guisande e Oliveira (São Pedro), Braga', '1992-11-10', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Alexandre Dias Novais de Sousa', '89', '226', 'Cabreiros e Passos (São Julião), Braga', '1991-5-22', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Manuel Azevedo Maia', '67', '219', 'Padim da Graça, Braga', '1995-8-10', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Nuno Alves Teixeira', '80', '238', 'Espinho, Braga', '1975-9-17', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Francisco José Vilão Matos Queiróz Peixoto', '93', '189', 'Arentim e Cunha, Braga', '1979-7-5', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Mariana Lino Lopes Costa', '104', '221', 'Espinho, Braga', '1981-8-19', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro André Correia Neves Parpot', '114', '206', 'Lamas, Braga', '1979-4-25', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ricardo Vieira Carvalho', '106', '152', 'Espinho, Braga', '1995-8-29', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joao Pedro Rodrigues Azevedo', '88', '208', 'Arentim e Cunha, Braga', '1991-10-12', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Pedro Oliveira Silva', '98', '263', 'Mire de Tibães, Braga', '1975-4-18', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ana Catarina Cardoso Gil', '73', '219', 'São Victor, Braga', '1990-9-11', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Carlos João Vieira Sousa Beiramar', '92', '198', 'Lomar e Arcos, Braga', '1979-10-13', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Henrique Veiga da Paz', '105', '156', 'Morreira e Trandeiras, Braga', '1984-7-31', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Marco Antonio Rodrigues Sampaio', '116', '212', 'Braga (Maximinos, Sé e Cividade), Braga', '1985-12-24', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tiago Henrique de Oliveira Magalhães', '87', '196', 'Ruilhe, Braga', '1982-5-12', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo Filipe Oliveira de Sousa Faria', '101', '189', 'Mire de Tibães, Braga', '1975-6-19', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Daniel da Silva Félix', '109', '195', 'Esporões, Braga', '1986-1-16', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Mário Sérgio Duarte Machado da Silva', '80', '190', 'Arentim e Cunha, Braga', '1982-1-1', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Rui Pedro Oliveira Serrano Morais', '95', '190', 'Cabreiros e Passos (São Julião), Braga', '1976-6-22', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Nuno Costa Neves', '91', '154', 'Gualtar, Braga', '1989-7-5', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Hugo Miguel Teles Silva', '113', '209', 'Ferreiros e Gondizalves, Braga', '1995-6-24', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Leonardo Barbosa Maia', '119', '209', 'Palmeira, Braga', '1975-7-29', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Pedro Miguel Borges Rodrigues', '82', '215', 'Braga (Maximinos, Sé e Cividade), Braga', '1993-2-14', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ivo dos Santos Oliveira', '81', '199', 'Adaúfe, Braga', '1991-3-20', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Maria Moutinho Figueiredo da Silva', '97', '165', 'Celeirós, Aveleda e Vimieiro, Braga', '1985-4-27', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Nelson Miguel de Oliveira Estevão', '106', '219', 'Lamas, Braga', '1975-3-24', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Carlos Viana Pereira Marques', '91', '168', 'Celeirós, Aveleda e Vimieiro, Braga', '1988-10-4', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Artur Drohobytskyy', '90', '202', 'Esporões, Braga', '1994-10-2', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joan Manuel Cedeño Rodriguez', '99', '213', 'Palmeira, Braga', '1975-11-30', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Filipe Gonçalves de Macedo', '115', '172', 'São Victor, Braga', '1977-6-10', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Filipe Simões de Abreu', '102', '174', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1982-9-12', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipe Pitrez Pereira Henriques', '103', '187', 'Nogueira, Fraião e Lamaçães, Braga', '1983-8-13', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tiago Taveira Gomes', '103', '168', 'Sobreposta, Braga', '1984-9-16', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João Miguel Fernandes Cerqueira Soares', '69', '239', 'Braga (Maximinos, Sé e Cividade), Braga', '1989-7-24', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Simão Freitas Monteiro', '95', '193', 'Nogueiró e Tenões, Braga', '1990-1-1', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Válter Ferreira Picas Carvalho', '93', '231', 'Lomar e Arcos, Braga', '1993-12-25', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Pedro Alexandre Gonçalves Ribeiro', '80', '228', 'Gualtar, Braga', '1991-9-11', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luís Pedro Barbosa Ferreira', '119', '211', 'Gualtar, Braga', '1978-10-11', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rafael Inácio Lourenço', '112', '215', 'Tadim, Braga', '1986-3-30', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ana Margarida Reis Maia Campos', '133', '190', 'Nogueira, Fraião e Lamaçães, Braga', '1975-10-27', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Daniela Sofia Pereira Arruda', '115', '202', 'Nogueiró e Tenões, Braga', '1986-5-21', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Luís Abreu Mendes', '89', '207', 'São Victor, Braga', '1987-10-14', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Paulo Ricardo Antunes Pereira', '136', '177', 'Esporões, Braga', '1993-1-15', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'António Manuel Almeida Pinto Bandeira Santos', '86', '206', 'Adaúfe, Braga', '1990-11-27', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luís Francisco Mendes Lopes', '85', '245', 'Figueiredo, Braga', '1977-9-30', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Carlos César Madureira Romano', '87', '204', 'Ferreiros e Gondizalves, Braga', '1991-3-3', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Nuno Azevedo Alves da Cunha', '73', '201', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1991-11-26', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Eduardo José Azevedo Ferreira Araújo', '110', '180', 'Real, Dume e Semelhe, Braga', '1983-5-10', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Hugo Fernandes Matias', '121', '170', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1983-9-17', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Daniel Freitas Ferreira', '92', '191', 'Nogueira, Fraião e Lamaçães, Braga', '1981-12-26', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Tiago Batoca Fernandes', '116', '202', 'Adaúfe, Braga', '1991-3-26', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Pedro Gomes Rodrigues dos Santos', '95', '208', 'Padim da Graça, Braga', '1989-1-18', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luis Miguel Arieira Ramos', '90', '203', 'Guisande e Oliveira (São Pedro), Braga', '1975-6-17', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Afonso Trindade Araújo de Pascoal Faria', '120', '168', 'Nogueiró e Tenões, Braga', '1995-12-16', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Alexandra de Barros Reigada', '105', '186', 'Vilaça e Fradelos, Braga', '1982-5-6', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Bruno Miguel Garcia Neto', '92', '179', 'Cabreiros e Passos (São Julião), Braga', '1993-8-8', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joao Pedro Oliveira Meira', '119', '211', 'Sequeira, Braga', '1978-4-6', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Aníbal Barbosa de Araújo', '139', '195', 'Real, Dume e Semelhe, Braga', '1995-7-31', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tânia Filipa Amorim da Rocha', '147', '227', 'Real, Dume e Semelhe, Braga', '1986-10-11', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'João da Cunha e Costa', '77', '198', 'Arentim e Cunha, Braga', '1990-1-25', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Constança Machado Aires Lobo Elias', '65', '219', 'Pedralva, Braga', '1987-7-25', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Nuno Miguel Freitas de Oliveira', '124', '218', 'Braga (Maximinos, Sé e Cividade), Braga', '1993-8-12', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Ricardo Marques da Costa Araújo', '139', '211', 'Vilaça e Fradelos, Braga', '1983-6-27', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Hugo Manuel Gomes Nogueira', '86', '189', 'São Vicente, Braga', '1991-3-2', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tiago Manuel da Silva Rego Macedo Alves', '108', '200', 'Padim da Graça, Braga', '1975-2-7', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joao Miguel Vasconcelos Ferreira Mesquita de Araujo', '104', '180', 'Tadim, Braga', '1990-1-11', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'António Maria de Araújo Serra Lobo Guerra', '101', '233', 'Morreira e Trandeiras, Braga', '1987-3-25', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Filipe José Vieira Barbosa', '103', '193', 'Priscos, Braga', '1979-10-5', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tiago Gomes Campos', '68', '158', 'Sequeira, Braga', '1976-3-5', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miguel Rúben Silva de Oliveira', '92', '192', 'São Vicente, Braga', '1995-12-25', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miguel Cardoso Pereira', '85', '215', 'Sobreposta, Braga', '1976-9-23', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Emanuel de Jesus Pedrosa Viana', '110', '204', 'Ferreiros e Gondizalves, Braga', '1986-10-27', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Daniel Fernandes Abreu', '103', '186', 'Tebosa, Braga', '1980-5-7', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Guilherme de Araujo Soares', '117', '235', 'Morreira e Trandeiras, Braga', '1983-5-17', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Rui Pedro Magalhães Torres', '115', '213', 'Esporões, Braga', '1989-9-5', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Eduardo Manuel Sousa Pereira', '101', '163', 'Sequeira, Braga', '1976-6-27', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Francisco Domingos Martins Oliveira', '97', '225', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1994-4-26', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Andre Loureiro Morais', '134', '198', 'Nogueira, Fraião e Lamaçães, Braga', '1995-3-16', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Leal Meireles Pereira', '80', '186', 'Tadim, Braga', '1977-9-11', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Miguel da Silva Brandão Gonçalves', '83', '196', 'Crespos e Pousada, Braga', '1988-10-12', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luís Pedro Martins Duarte', '127', '185', 'Nogueira, Fraião e Lamaçães, Braga', '1987-9-12', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Francisco Egídio Coutinho Martins Correia', '118', '193', 'Espinho, Braga', '1985-1-6', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Gonçalo Sanches Garcia', '98', '213', 'Arentim e Cunha, Braga', '1985-10-7', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Pedro Rafael Bernardo Medeiros', '108', '180', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1984-7-30', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Mariana de Oliveira Pereira', '164', '192', 'Nogueiró e Tenões, Braga', '1977-7-2', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Gonçalo José Santiago Pereira', '98', '182', 'Lomar e Arcos, Braga', '1984-10-28', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Mário Rui Sendas Rocha', '111', '186', 'Priscos, Braga', '1980-1-15', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Miguel André da Silva Solino', '85', '213', 'Figueiredo, Braga', '1987-2-12', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Arthur Cardoso Franca', '62', '223', 'Arentim e Cunha, Braga', '1986-1-6', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Maria Laura de Araújo Barbosa', '124', '181', 'Morreira e Trandeiras, Braga', '1989-9-24', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Diogo Pinto Ribeiro', '84', '178', 'São Vicente, Braga', '1977-1-18', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Bruno Miguel Pinheiro Alves', '121', '206', 'Lomar e Arcos, Braga', '1975-11-17', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Celso André de Carvalho Rodrigues', '68', '195', 'Nogueira, Fraião e Lamaçães, Braga', '1986-2-16', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Filipe Chaves', '105', '165', 'Sobreposta, Braga', '1995-5-31', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Miguel Pinto Rio', '128', '190', 'Palmeira, Braga', '1985-3-31', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Carlos Garcia Linhares', '94', '186', 'Este (São Pedro e São Mamede), Braga', '1980-3-21', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Renata Gomes Dias Ribeiro', '57', '219', 'Nogueira, Fraião e Lamaçães, Braga', '1975-8-29', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joao Marcelo Caseiro Cagigal Olival', '106', '164', 'Braga (Maximinos, Sé e Cividade), Braga', '1982-4-21', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Mariana Gonçalves Marques', '122', '171', 'Este (São Pedro e São Mamede), Braga', '1982-6-8', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Martinha João Trindade Ribeiro', '99', '220', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1986-10-5', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Sílvia Maria Acosta Roca', '83', '173', 'Este (São Pedro e São Mamede), Braga', '1993-1-22', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rosa Inês Carvalho Marinho', '120', '176', 'Esporões, Braga', '1975-1-27', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Manuel da Rocha Rodrigues', '126', '185', 'Braga (Maximinos, Sé e Cividade), Braga', '1976-2-19', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Mendes Pinto', '106', '200', 'Esporões, Braga', '1987-1-14', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Alves dos Santos', '120', '218', 'Lamas, Braga', '1979-6-17', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Diogo Alexandre Portela Teixeira', '105', '154', 'Cabreiros e Passos (São Julião), Braga', '1979-7-19', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Mateus Pires Presa', '102', '164', 'Crespos e Pousada, Braga', '1988-7-8', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'António Alexandre Carvalho Lindo', '114', '213', 'Guisande e Oliveira (São Pedro), Braga', '1987-4-21', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Fernanda Manuela Alves Dias', '100', '182', 'Cabreiros e Passos (São Julião), Braga', '1983-5-29', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Eduardo Joao Gomes Teixeira da Costa', '119', '211', 'Tadim, Braga', '1975-10-20', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Peter Ferreira Vala', '131', '235', 'Lamas, Braga', '1983-1-20', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Rita Miranda Rosendo', '84', '196', 'Crespos e Pousada, Braga', '1992-1-5', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ivo Alexandre Pereira Baixo', '106', '174', 'Arentim e Cunha, Braga', '1988-12-28', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Luís Mário Macedo Ribeiro', '113', '211', 'Crespos e Pousada, Braga', '1989-10-15', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Araújo Ferreira', '111', '186', 'Nogueira, Fraião e Lamaçães, Braga', '1990-7-6', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'José Aventino Moura Saraiva de Menezes', '61', '234', 'Sequeira, Braga', '1978-6-12', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Rui Alexandre Dias Neto', '118', '171', 'São Vicente, Braga', '1995-9-25', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Duarte Araújo', '97', '237', 'Lomar e Arcos, Braga', '1980-12-19', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Nelson Correia Faria', '132', '193', 'Palmeira, Braga', '1995-1-10', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'André Filipe da Silva Marques', '70', '165', 'Braga (Maximinos, Sé e Cividade), Braga', '1988-5-13', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Maria Manuela Soares Silva', '113', '160', 'Nogueiró e Tenões, Braga', '1979-3-4', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana João Dias de Almeida', '88', '187', 'Este (São Pedro e São Mamede), Braga', '1975-7-19', 7);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-2-21T20:45', 319, 'Salto em Comprimento', 1);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-9-24T17:8', 694, 'Salto em Altura', 2);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2020-4-6T12:1', 556, 'Estafetas', 3);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-6-29T18:47', 1180, 'Sprint 60m', 4);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-11-4T15:49', 1073, 'Sprint 100m', 5);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2020-6-21T17:21', 593, 'Sprint 200m', 6);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-12-24T17:19', 961, 'Sprint 400m', 7);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-6-13T16:32', 1255, 'Barreiras 60m', 8);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-7-27T10:43', 631, 'Barreiras 100m', 9);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2020-1-19T18:40', 438, 'Barreiras 400m', 10);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2020-10-21T18:32', 456, 'Lançamento do Peso', 11);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-12-24T18:10', 1540, 'Lançamento do Martelo', 12);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2020-1-1T10:57', 1484, 'Lançamento do Dardo', 13);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-6-4T19:28', 1512, 'Lançamento do Disco', 14);
INSERT INTO Prova (data_hora, duração, nome, id_modalidade) VALUES ('2021-11-16T12:59', 652, 'Maratona', 15);
INSERT INTO TestesClinicos (nome, realizado, preço, duração, data_hora) VALUES ('Análises', 0, 13, 18, '2020-9-30T11:1');
INSERT INTO Teste_Profissional (id_teste_clinico, id_profissional) VALUES (1, 107);
INSERT INTO Atleta_Testes_Clinicos (id_teste_clinico, id_atleta) VALUES (1, 225);
INSERT INTO TestesClinicos (nome, realizado, preço, duração, data_hora) VALUES ('Controlo Anti-Doping', 1, 7, 19, '2021-5-1T18:8');
INSERT INTO Teste_Profissional (id_teste_clinico, id_profissional) VALUES (2, 28);
INSERT INTO Atleta_Testes_Clinicos (id_teste_clinico, id_atleta) VALUES (2, 193);
