INSERT INTO Modalidade (nome) VALUES ('Salto em Comprimento');
INSERT INTO Modalidade (nome) VALUES ('Salto em Altura');
INSERT INTO Modalidade (nome) VALUES ('Estafetas');
INSERT INTO Modalidade (nome) VALUES ('Sprint 60m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 100m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 200m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 400m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 60m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 100m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 400m');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Peso');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Martelo');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Dardo');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Disco');
INSERT INTO Modalidade (nome) VALUES ('Maratona');
INSERT INTO Profissional (nome) VALUES ('Constantino');
INSERT INTO Profissional (nome) VALUES ('Tarciso');
INSERT INTO Profissional (nome) VALUES ('Olivia');
INSERT INTO Profissional (nome) VALUES ('Derick');
INSERT INTO Profissional (nome) VALUES ('Khadija');
INSERT INTO Profissional (nome) VALUES ('Papa-Ndiogou');
INSERT INTO Profissional (nome) VALUES ('Marius');
INSERT INTO Profissional (nome) VALUES ('Manish');
INSERT INTO Profissional (nome) VALUES ('Vinildo');
INSERT INTO Profissional (nome) VALUES ('Humaira');
INSERT INTO Profissional (nome) VALUES ('Rayna');
INSERT INTO Profissional (nome) VALUES ('Rafia');
INSERT INTO Profissional (nome) VALUES ('Nelson');
INSERT INTO Profissional (nome) VALUES ('Jamie');
INSERT INTO Profissional (nome) VALUES ('Maura');
INSERT INTO Profissional (nome) VALUES ('Manteg');
INSERT INTO Profissional (nome) VALUES ('Nayra');
INSERT INTO Profissional (nome) VALUES ('Adame');
INSERT INTO Profissional (nome) VALUES ('Lisandra');
INSERT INTO Profissional (nome) VALUES ('Enzo');
INSERT INTO Profissional (nome) VALUES ('Helaine');
INSERT INTO Profissional (nome) VALUES ('Kadirkhan');
INSERT INTO Profissional (nome) VALUES ('Lavonne');
INSERT INTO Profissional (nome) VALUES ('Seerat');
INSERT INTO Profissional (nome) VALUES ('Mansirat');
INSERT INTO Profissional (nome) VALUES ('Steven');
INSERT INTO Profissional (nome) VALUES ('Brianna');
INSERT INTO Profissional (nome) VALUES ('Stanislawa');
INSERT INTO Profissional (nome) VALUES ('Niah');
INSERT INTO Profissional (nome) VALUES ('Florinda');
INSERT INTO Profissional (nome) VALUES ('Patrício');
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Alberto Rui Vilaverde Monteiro da Silva', '141', '200', 'Merelim (São Pedro) e Frossos, Braga', '1979-7-26', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Alexandre Esteves Miranda', '102', '188', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1991-4-2', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Luísa Pereira de César', '130', '170', 'Pedralva, Braga', '1989-6-25', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Margarida Reis Maia Campos', '73', '248', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1986-11-3', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Rita Miranda Rosendo', '130', '205', 'Braga (Maximinos, Sé e Cividade), Braga', '1990-5-29', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Alves dos Santos', '79', '209', 'Sobreposta, Braga', '1993-10-29', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Bernardo Coelho Nunes', '152', '155', 'Guisande e Oliveira (São Pedro), Braga', '1977-11-25', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Daniel Freitas Ferreira', '111', '182', 'Sobreposta, Braga', '1988-9-10', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Sousa Figueiredo', '105', '206', 'Esporões, Braga', '1988-10-14', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Beatriz Freitas Rocha', '105', '228', 'Celeirós, Aveleda e Vimieiro, Braga', '1978-7-3', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bernardo José Barbosa Alves', '82', '204', 'Priscos, Braga', '1979-12-31', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Alexandre Dias Novais de Sousa', '97', '196', 'Ruilhe, Braga', '1988-11-14', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Alves Martins Carvalho', '114', '241', 'São Victor, Braga', '1985-12-9', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Miguel Faria Fernandes', '81', '178', 'Nogueiró e Tenões, Braga', '1977-2-12', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Carlos César Madureira Romano', '109', '186', 'Arentim e Cunha, Braga', '1986-6-6', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Catarina Freitas da Cruz', '98', '180', 'Guisande e Oliveira (São Pedro), Braga', '1986-2-20', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Celso André de Carvalho Rodrigues', '104', '214', 'Esporões, Braga', '1981-1-7', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Daniela Eduarda Cruz Fernandes', '96', '206', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1975-5-12', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Daniela Sofia Pereira Arruda', '84', '198', 'Arentim e Cunha, Braga', '1994-4-28', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Araújo Ferreira', '98', '165', 'Ferreiros e Gondizalves, Braga', '1989-2-16', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Miguel Alves Rocha', '77', '226', 'Lomar e Arcos, Braga', '1979-1-31', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Paulo Lopes de Vasconcelos', '157', '218', 'Padim da Graça, Braga', '1985-8-31', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Pinto Ribeiro', '57', '172', 'Merelim (São Pedro) e Frossos, Braga', '1992-11-11', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Duarte Manuel Vilar de Oliveira', '117', '187', 'Celeirós, Aveleda e Vimieiro, Braga', '1978-9-19', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Eduardo José Azevedo Ferreira Araújo', '114', '206', 'Este (São Pedro e São Mamede), Braga', '1987-3-31', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Fábio Fernandes Silva', '85', '199', 'Guisande e Oliveira (São Pedro), Braga', '1985-9-8', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Fernanda Manuela Alves Dias', '76', '230', 'Ferreiros e Gondizalves, Braga', '1984-6-14', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Filipe Gonçalves de Macedo', '77', '202', 'Braga (Maximinos, Sé e Cividade), Braga', '1979-10-1', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Filipe José Vieira Barbosa', '102', '208', 'Cabreiros e Passos (São Julião), Braga', '1977-3-14', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Francisco Egídio Coutinho Martins Correia', '89', '203', 'Tebosa, Braga', '1988-12-30', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Gonçalo Leal da Mota Meireles Moreira', '106', '230', 'Real, Dume e Semelhe, Braga', '1984-11-12', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Goncalo Nuno Esperança Quesado', '148', '188', 'Lamas, Braga', '1989-11-12', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Guilherme de Araujo Soares', '96', '212', 'Sobreposta, Braga', '1976-7-14', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Guilherme João Cerqueira da Mota Miranda', '127', '199', 'Priscos, Braga', '1985-8-7', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Helena Poças Martins', '87', '157', 'Merelim (São Pedro) e Frossos, Braga', '1990-2-6', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Henrique Veiga da Paz', '110', '229', 'Crespos e Pousada, Braga', '1983-2-18', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo André Coelho Cardoso', '82', '218', 'Esporões, Braga', '1989-7-6', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo André da Silva Veloso Moreira', '63', '176', 'Priscos, Braga', '1988-3-8', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo Fernandes Matias', '77', '182', 'Nogueira, Fraião e Lamaçães, Braga', '1991-3-12', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo Filipe Duarte Carvalho', '115', '186', 'Celeirós, Aveleda e Vimieiro, Braga', '1990-4-10', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joana Esteves Dantas', '101', '184', 'Ruilhe, Braga', '1994-8-1', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joan Manuel Cedeño Rodriguez', '85', '178', 'Mire de Tibães, Braga', '1978-11-10', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Bernardo Coutinho Barreiros de Freitas', '79', '205', 'Esporões, Braga', '1988-12-25', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Carlos Pereira Rodrigues', '98', '220', 'Celeirós, Aveleda e Vimieiro, Braga', '1990-4-18', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João da Cunha e Costa', '108', '201', 'Pedralva, Braga', '1983-11-1', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Duarte Vila Verde Silva', '97', '190', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1976-1-9', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Manuel da Rocha Rodrigues', '100', '180', 'Sobreposta, Braga', '1993-12-13', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Manuel Silva Antunes', '78', '182', 'Crespos e Pousada, Braga', '1983-6-10', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Nuno Brandão Silva', '97', '214', 'Figueiredo, Braga', '1994-2-2', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Nuno Cardoso Gonçalves de Abreu', '85', '170', 'Lomar e Arcos, Braga', '1984-9-11', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Dias Fernandes', '114', '211', 'Sobreposta, Braga', '1982-3-3', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Magalhães Teixeira', '91', '190', 'Merelim (São Pedro) e Frossos, Braga', '1984-9-5', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Oliveira Meira', '93', '214', 'Sobreposta, Braga', '1995-4-18', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Rodrigues Azevedo', '158', '200', 'Priscos, Braga', '1995-9-13', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Tiago Oliveira Sousa Nogueira Lopes', '151', '196', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1984-8-12', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joaquim Francisco Barata Simões', '103', '168', 'Espinho, Braga', '1980-2-23', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Manuel Loureiro Vieira', '96', '204', 'Palmeira, Braga', '1987-10-15', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Miguel da Silva Brandão Gonçalves', '133', '184', 'Tebosa, Braga', '1984-6-21', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'José Diogo Xavier Monteiro', '103', '234', 'Priscos, Braga', '1981-8-16', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Alberto Diogo Pereira de Lima', '102', '205', 'Sequeira, Braga', '1985-8-21', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Daniel da Silva Félix', '108', '187', 'Ruilhe, Braga', '1984-3-24', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luis Filipe da Silva Costa', '75', '213', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1994-4-1', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Miguel Aquino Silva', '57', '196', 'São Vicente, Braga', '1987-1-28', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Miguel Arrepia Ferreira', '93', '191', 'Cabreiros e Passos (São Julião), Braga', '1977-11-24', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Pedro da Silva Vila', '100', '227', 'Pedralva, Braga', '1975-6-2', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Marco Alexandre Félix de Lima', '129', '205', 'Adaúfe, Braga', '1983-11-23', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Marco Antonio Rodrigues Sampaio', '107', '182', 'Guisande e Oliveira (São Pedro), Braga', '1979-10-10', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Francisca Tavares Martins Fernandes', '103', '202', 'Crespos e Pousada, Braga', '1988-8-23', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Inês de Azevedo Mouroa Alves', '88', '159', 'Palmeira, Braga', '1980-6-14', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria José Borges Pires', '90', '198', 'Real, Dume e Semelhe, Braga', '1979-8-30', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Laura de Araújo Barbosa', '104', '214', 'Esporões, Braga', '1991-6-5', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Luísa Faria Silva', '112', '240', 'Ferreiros e Gondizalves, Braga', '1989-6-26', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Miguel Albuquerque Regueiras', '111', '167', 'Real, Dume e Semelhe, Braga', '1990-7-24', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Mariana Gonçalves Marques', '101', '193', 'Figueiredo, Braga', '1989-4-19', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Mariana Lino Lopes Costa', '115', '246', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1987-1-8', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miguel Cardoso Pereira', '72', '194', 'Celeirós, Aveleda e Vimieiro, Braga', '1980-6-2', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miguel Rúben Silva de Oliveira', '83', '197', 'Ferreiros e Gondizalves, Braga', '1982-10-10', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Nélson Miguel de Oliveira Estevão', '109', '192', 'Celeirós, Aveleda e Vimieiro, Braga', '1991-5-25', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Nuno Azevedo Alves da Cunha', '92', '222', 'Nogueiró e Tenões, Braga', '1988-8-2', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro André Correia Neves Parpot', '148', '163', 'Sobreposta, Braga', '1995-9-30', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Daniel Fernandes Abreu', '104', '184', 'Real, Dume e Semelhe, Braga', '1993-8-16', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Filipe Carvalho Barbosa', '127', '205', 'São Vicente, Braga', '1981-6-9', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Gomes Machado Monteiro Fernandes', '57', '209', 'Braga (Maximinos, Sé e Cividade), Braga', '1976-3-12', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Borges Rodrigues', '107', '194', 'Merelim (São Pedro) e Frossos, Braga', '1995-1-5', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Queiros Gomes', '105', '190', 'Real, Dume e Semelhe, Braga', '1982-10-13', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Nuno Fernandes Freitas', '64', '182', 'Guisande e Oliveira (São Pedro), Braga', '1989-4-11', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Rafael Bernardo Medeiros', '96', '157', 'Crespos e Pousada, Braga', '1994-2-26', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Rafael Martins de Oliveira', '124', '171', 'Morreira e Trandeiras, Braga', '1992-8-29', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Peter Ferreira Vala', '99', '200', 'Lomar e Arcos, Braga', '1975-9-2', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rafael Antunes Simões', '114', '178', 'Padim da Graça, Braga', '1977-4-28', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Renato Jorge Cruzinha da Silva', '111', '187', 'Nogueiró e Tenões, Braga', '1981-4-9', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo José Santos Veloso', '91', '223', 'Mire de Tibães, Braga', '1984-9-28', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Miguel da Silva Pereira', '102', '218', 'Lomar e Arcos, Braga', '1990-6-28', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Vieira Carvalho', '98', '214', 'Lamas, Braga', '1976-5-30', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Alexandre Dias Neto', '128', '210', 'Cabreiros e Passos (São Julião), Braga', '1975-8-16', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Filipe Chaves', '112', '180', 'Ruilhe, Braga', '1976-7-16', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Filipe Traila de Sousa', '106', '186', 'Ruilhe, Braga', '1978-2-3', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Miguel Pimenta e Cunha', '121', '240', 'Crespos e Pousada, Braga', '1979-7-29', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Nuno Borges Cruz Oliveira', '104', '213', 'Gualtar, Braga', '1989-10-3', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Pedro Neto Reis', '106', '200', 'Real, Dume e Semelhe, Braga', '1992-7-2', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Shahzod Yusupov', '97', '201', 'Lamas, Braga', '1990-4-5', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tânia Filipa Amorim da Rocha', '135', '203', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1986-6-14', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Tiago Gabriel Pereira da Silva', '67', '201', 'Tebosa, Braga', '1984-10-18', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Tiago Gomes Campos', '70', '183', 'Figueiredo, Braga', '1984-8-17', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Válter Ferreira Picas Carvalho', '124', '192', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1992-11-9', 5);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-1-4T18:50', 406, 1);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-12-14T12:13', 1166, 2);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-12-18T17:27', 204, 3);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-7-21T13:7', 1471, 4);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-11-23T20:34', 1156, 5);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-12-27T12:4', 1260, 6);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-4-12T19:30', 1175, 7);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-3-26T9:35', 1344, 8);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-10-21T9:51', 532, 9);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-3-6T17:4', 556, 10);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-8-19T20:13', 964, 11);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-4-25T15:22', 543, 12);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-2-20T9:33', 1469, 13);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-8-10T9:14', 668, 14);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-12-16T17:20', 323, 15);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 11, '2020-12-07T14:30', 18, 31);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 12, '2019-04-02T14:15', 18, 22);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 10, '2021-11-22T12:30', 18, 22);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 10, '2019-06-19T17:00', 21, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 5, '2020-11-02T09:15', 21, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 15, '2020-02-27T09:30', 29, 14);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 9, '2019-04-15T15:15', 29, 6);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 5, '2021-06-24T15:45', 29, 14);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 14, '2021-12-22T16:00', 34, 30);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 13, '2019-07-31T15:15', 34, 5);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 10, '2021-11-17T11:00', 34, 8);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 11, '2019-03-24T17:15', 23, 30);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 9, '2021-11-15T11:00', 77, 11);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 6, '2021-07-01T09:45', 104, 12);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 13, '2020-11-05T16:15', 104, 12);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 12, '2019-12-25T15:30', 104, 31);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 5, '2020-09-29T13:45', 51, 25);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 11, '2021-05-30T09:45', 69, 24);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 9, '2019-07-12T16:00', 69, 24);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 11, '2019-05-22T13:15', 69, 27);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 7, '2019-10-11T12:30', 33, 11);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 10, '2021-01-19T11:30', 96, 10);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 7, '2020-08-26T15:45', 81, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 5, '2019-10-02T16:15', 81, 31);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 6, '2021-11-25T13:15', 93, 18);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 6, '2020-05-31T11:15', 93, 22);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 11, '2021-02-17T17:45', 82, 9);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 10, '2019-07-25T13:30', 40, 7);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 13, '2021-07-26T11:00', 40, 5);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 5, '2021-10-13T14:45', 101, 18);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 10, '2020-11-20T12:00', 101, 17);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 8, '2019-11-07T14:45', 101, 19);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 13, '2019-07-03T16:15', 31, 29);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 6, '2021-02-07T11:45', 31, 30);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 1, 9, '2020-01-03T15:45', 97, 14);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 6, '2020-01-04T14:30', 4, 10);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Análises', 0, 9, '2020-01-05T16:00', 98, 7);
