INSERT INTO Modalidade (nome) VALUES ('Salto em Comprimento');
INSERT INTO Modalidade (nome) VALUES ('Salto em Altura');
INSERT INTO Modalidade (nome) VALUES ('Estafetas');
INSERT INTO Modalidade (nome) VALUES ('Sprint 60m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 100m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 200m');
INSERT INTO Modalidade (nome) VALUES ('Sprint 400m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 60m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 100m');
INSERT INTO Modalidade (nome) VALUES ('Barreiras 400m');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Peso');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Martelo');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Dardo');
INSERT INTO Modalidade (nome) VALUES ('Lançamento do Disco');
INSERT INTO Modalidade (nome) VALUES ('Maratona');
INSERT INTO Profissional (nome) VALUES ('Constantino');
INSERT INTO Profissional (nome) VALUES ('Tarciso');
INSERT INTO Profissional (nome) VALUES ('Olivia');
INSERT INTO Profissional (nome) VALUES ('Derick');
INSERT INTO Profissional (nome) VALUES ('Khadija');
INSERT INTO Profissional (nome) VALUES ('Papa-Ndiogou');
INSERT INTO Profissional (nome) VALUES ('Marius');
INSERT INTO Profissional (nome) VALUES ('Manish');
INSERT INTO Profissional (nome) VALUES ('Vinildo');
INSERT INTO Profissional (nome) VALUES ('Humaira');
INSERT INTO Profissional (nome) VALUES ('Rayna');
INSERT INTO Profissional (nome) VALUES ('Rafia');
INSERT INTO Profissional (nome) VALUES ('Nelson');
INSERT INTO Profissional (nome) VALUES ('Jamie');
INSERT INTO Profissional (nome) VALUES ('Maura');
INSERT INTO Profissional (nome) VALUES ('Manteg');
INSERT INTO Profissional (nome) VALUES ('Nayra');
INSERT INTO Profissional (nome) VALUES ('Adame');
INSERT INTO Profissional (nome) VALUES ('Lisandra');
INSERT INTO Profissional (nome) VALUES ('Enzo');
INSERT INTO Profissional (nome) VALUES ('Helaine');
INSERT INTO Profissional (nome) VALUES ('Kadirkhan');
INSERT INTO Profissional (nome) VALUES ('Lavonne');
INSERT INTO Profissional (nome) VALUES ('Seerat');
INSERT INTO Profissional (nome) VALUES ('Mansirat');
INSERT INTO Profissional (nome) VALUES ('Steven');
INSERT INTO Profissional (nome) VALUES ('Brianna');
INSERT INTO Profissional (nome) VALUES ('Stanislawa');
INSERT INTO Profissional (nome) VALUES ('Niah');
INSERT INTO Profissional (nome) VALUES ('Florinda');
INSERT INTO Profissional (nome) VALUES ('Patrício');
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Alberto Rui Vilaverde Monteiro da Silva', '96', '203', 'Merelim (São Pedro) e Frossos, Braga', '1979-7-26', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Alexandre Esteves Miranda', '107', '212', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1991-4-2', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Luísa Pereira de César', '86', '173', 'Pedralva, Braga', '1989-6-25', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Margarida Reis Maia Campos', '96', '232', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1986-11-3', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Ana Rita Miranda Rosendo', '105', '180', 'Braga (Maximinos, Sé e Cividade), Braga', '1990-5-29', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Alves dos Santos', '101', '203', 'Sobreposta, Braga', '1993-10-29', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Bernardo Coelho Nunes', '108', '205', 'Guisande e Oliveira (São Pedro), Braga', '1977-11-25', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Daniel Freitas Ferreira', '93', '223', 'Sobreposta, Braga', '1988-9-10', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'André Sousa Figueiredo', '80', '220', 'Esporões, Braga', '1988-10-14', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Beatriz Freitas Rocha', '55', '158', 'Celeirós, Aveleda e Vimieiro, Braga', '1978-7-3', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bernardo José Barbosa Alves', '76', '188', 'Priscos, Braga', '1979-12-31', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Alexandre Dias Novais de Sousa', '125', '215', 'Ruilhe, Braga', '1988-11-14', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Alves Martins Carvalho', '86', '218', 'São Victor, Braga', '1985-12-9', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Bruno Miguel Faria Fernandes', '116', '207', 'Nogueiró e Tenões, Braga', '1977-2-12', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Carlos César Madureira Romano', '114', '230', 'Arentim e Cunha, Braga', '1986-6-6', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Catarina Freitas da Cruz', '59', '198', 'Guisande e Oliveira (São Pedro), Braga', '1986-2-20', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Celso André de Carvalho Rodrigues', '114', '188', 'Esporões, Braga', '1981-1-7', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Daniela Eduarda Cruz Fernandes', '93', '208', 'Escudeiros e Penso (Santo Estêvão e São Vicente), Braga', '1975-5-12', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Daniela Sofia Pereira Arruda', '112', '212', 'Arentim e Cunha, Braga', '1994-4-28', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Araújo Ferreira', '85', '204', 'Ferreiros e Gondizalves, Braga', '1989-2-16', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Miguel Alves Rocha', '119', '236', 'Lomar e Arcos, Braga', '1979-1-31', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Paulo Lopes de Vasconcelos', '110', '201', 'Padim da Graça, Braga', '1985-8-31', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Diogo Pinto Ribeiro', '98', '214', 'Merelim (São Pedro) e Frossos, Braga', '1992-11-11', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Duarte Manuel Vilar de Oliveira', '114', '208', 'Celeirós, Aveleda e Vimieiro, Braga', '1978-9-19', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Eduardo José Azevedo Ferreira Araújo', '98', '192', 'Este (São Pedro e São Mamede), Braga', '1987-3-31', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Fábio Fernandes Silva', '101', '216', 'Guisande e Oliveira (São Pedro), Braga', '1985-9-8', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Fernanda Manuela Alves Dias', '87', '207', 'Ferreiros e Gondizalves, Braga', '1984-6-14', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Filipe Gonçalves de Macedo', '130', '204', 'Braga (Maximinos, Sé e Cividade), Braga', '1979-10-1', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Filipe José Vieira Barbosa', '84', '188', 'Cabreiros e Passos (São Julião), Braga', '1977-3-14', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Francisco Egídio Coutinho Martins Correia', '95', '196', 'Tebosa, Braga', '1988-12-30', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Gonçalo Leal da Mota Meireles Moreira', '98', '198', 'Real, Dume e Semelhe, Braga', '1984-11-12', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Goncalo Nuno Esperança Quesado', '79', '213', 'Lamas, Braga', '1989-11-12', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Guilherme de Araujo Soares', '132', '253', 'Sobreposta, Braga', '1976-7-14', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Guilherme João Cerqueira da Mota Miranda', '50', '221', 'Priscos, Braga', '1985-8-7', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Helena Poças Martins', '139', '203', 'Merelim (São Pedro) e Frossos, Braga', '1990-2-6', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Henrique Veiga da Paz', '102', '200', 'Crespos e Pousada, Braga', '1983-2-18', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo André Coelho Cardoso', '94', '226', 'Esporões, Braga', '1989-7-6', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo André da Silva Veloso Moreira', '105', '185', 'Priscos, Braga', '1988-3-8', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo Fernandes Matias', '93', '187', 'Nogueira, Fraião e Lamaçães, Braga', '1991-3-12', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Hugo Filipe Duarte Carvalho', '80', '207', 'Celeirós, Aveleda e Vimieiro, Braga', '1990-4-10', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Joana Esteves Dantas', '86', '177', 'Ruilhe, Braga', '1994-8-1', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joan Manuel Cedeño Rodriguez', '68', '224', 'Mire de Tibães, Braga', '1978-11-10', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Bernardo Coutinho Barreiros de Freitas', '68', '198', 'Esporões, Braga', '1988-12-25', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Carlos Pereira Rodrigues', '122', '173', 'Celeirós, Aveleda e Vimieiro, Braga', '1990-4-18', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João da Cunha e Costa', '82', '211', 'Pedralva, Braga', '1983-11-1', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Duarte Vila Verde Silva', '77', '183', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1976-1-9', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Manuel da Rocha Rodrigues', '84', '197', 'Sobreposta, Braga', '1993-12-13', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Manuel Silva Antunes', '141', '198', 'Crespos e Pousada, Braga', '1983-6-10', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Nuno Brandão Silva', '113', '191', 'Figueiredo, Braga', '1994-2-2', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Nuno Cardoso Gonçalves de Abreu', '131', '180', 'Lomar e Arcos, Braga', '1984-9-11', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Dias Fernandes', '71', '198', 'Sobreposta, Braga', '1982-3-3', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Magalhães Teixeira', '84', '214', 'Merelim (São Pedro) e Frossos, Braga', '1984-9-5', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Oliveira Meira', '82', '193', 'Sobreposta, Braga', '1995-4-18', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Pedro Rodrigues Azevedo', '138', '202', 'Priscos, Braga', '1995-9-13', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'João Tiago Oliveira Sousa Nogueira Lopes', '100', '211', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1984-8-12', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Joaquim Francisco Barata Simões', '111', '217', 'Espinho, Braga', '1980-2-23', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Manuel Loureiro Vieira', '138', '191', 'Palmeira, Braga', '1987-10-15', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Jorge Miguel da Silva Brandão Gonçalves', '105', '185', 'Tebosa, Braga', '1984-6-21', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'José Diogo Xavier Monteiro', '63', '210', 'Priscos, Braga', '1981-8-16', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Alberto Diogo Pereira de Lima', '129', '189', 'Sequeira, Braga', '1985-8-21', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Daniel da Silva Félix', '74', '222', 'Ruilhe, Braga', '1984-3-24', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luis Filipe da Silva Costa', '98', '215', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1994-4-1', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Miguel Aquino Silva', '82', '214', 'São Vicente, Braga', '1987-1-28', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Miguel Arrepia Ferreira', '87', '220', 'Cabreiros e Passos (São Julião), Braga', '1977-11-24', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Luís Pedro da Silva Vila', '87', '172', 'Pedralva, Braga', '1975-6-2', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Marco Alexandre Félix de Lima', '71', '209', 'Adaúfe, Braga', '1983-11-23', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Marco Antonio Rodrigues Sampaio', '136', '226', 'Guisande e Oliveira (São Pedro), Braga', '1979-10-10', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Francisca Tavares Martins Fernandes', '113', '165', 'Crespos e Pousada, Braga', '1988-8-23', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Inês de Azevedo Mouroa Alves', '104', '191', 'Palmeira, Braga', '1980-6-14', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria José Borges Pires', '112', '180', 'Real, Dume e Semelhe, Braga', '1979-8-30', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Laura de Araújo Barbosa', '118', '216', 'Esporões, Braga', '1991-6-5', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Luísa Faria Silva', '113', '227', 'Ferreiros e Gondizalves, Braga', '1989-6-26', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Maria Miguel Albuquerque Regueiras', '111', '213', 'Real, Dume e Semelhe, Braga', '1990-7-24', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Mariana Gonçalves Marques', '121', '204', 'Figueiredo, Braga', '1989-4-19', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Mariana Lino Lopes Costa', '95', '224', 'Braga (São José de São Lázaro e São João do Souto), Braga', '1987-1-8', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miguel Cardoso Pereira', '95', '215', 'Celeirós, Aveleda e Vimieiro, Braga', '1980-6-2', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Miguel Rúben Silva de Oliveira', '92', '171', 'Ferreiros e Gondizalves, Braga', '1982-10-10', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Nélson Miguel de Oliveira Estevão', '115', '212', 'Celeirós, Aveleda e Vimieiro, Braga', '1991-5-25', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Nuno Azevedo Alves da Cunha', '97', '189', 'Nogueiró e Tenões, Braga', '1988-8-2', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro André Correia Neves Parpot', '84', '195', 'Sobreposta, Braga', '1995-9-30', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Daniel Fernandes Abreu', '91', '218', 'Real, Dume e Semelhe, Braga', '1993-8-16', 5);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Filipe Carvalho Barbosa', '84', '207', 'São Vicente, Braga', '1981-6-9', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Gomes Machado Monteiro Fernandes', '89', '186', 'Braga (Maximinos, Sé e Cividade), Braga', '1976-3-12', 1);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Borges Rodrigues', '96', '213', 'Merelim (São Pedro) e Frossos, Braga', '1995-1-5', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Miguel Queiros Gomes', '107', '194', 'Real, Dume e Semelhe, Braga', '1982-10-13', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Nuno Fernandes Freitas', '98', '186', 'Guisande e Oliveira (São Pedro), Braga', '1989-4-11', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Rafael Bernardo Medeiros', '77', '193', 'Crespos e Pousada, Braga', '1994-2-26', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Pedro Rafael Martins de Oliveira', '95', '200', 'Morreira e Trandeiras, Braga', '1992-8-29', 6);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Peter Ferreira Vala', '84', '240', 'Lomar e Arcos, Braga', '1975-9-2', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rafael Antunes Simões', '94', '222', 'Padim da Graça, Braga', '1977-4-28', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Renato Jorge Cruzinha da Silva', '102', '224', 'Nogueiró e Tenões, Braga', '1981-4-9', 11);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo José Santos Veloso', '99', '194', 'Mire de Tibães, Braga', '1984-9-28', 7);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Miguel da Silva Pereira', '120', '187', 'Lomar e Arcos, Braga', '1990-6-28', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Ricardo Vieira Carvalho', '59', '190', 'Lamas, Braga', '1976-5-30', 9);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Alexandre Dias Neto', '91', '176', 'Cabreiros e Passos (São Julião), Braga', '1975-8-16', 12);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Filipe Chaves', '87', '195', 'Ruilhe, Braga', '1976-7-16', 8);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Filipe Traila de Sousa', '86', '244', 'Ruilhe, Braga', '1978-2-3', 4);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Miguel Pimenta e Cunha', '119', '210', 'Crespos e Pousada, Braga', '1979-7-29', 15);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Nuno Borges Cruz Oliveira', '77', '216', 'Gualtar, Braga', '1989-10-3', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Rui Pedro Neto Reis', '104', '169', 'Real, Dume e Semelhe, Braga', '1992-7-2', 3);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Shahzod Yusupov', '93', '207', 'Lamas, Braga', '1990-4-5', 14);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('F', 'Tânia Filipa Amorim da Rocha', '116', '178', 'Merelim (São Paio), Panoias e Parada de Tibães, Braga', '1986-6-14', 2);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Tiago Gabriel Pereira da Silva', '81', '201', 'Tebosa, Braga', '1984-10-18', 13);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Tiago Gomes Campos', '90', '183', 'Figueiredo, Braga', '1984-8-17', 10);
INSERT INTO Atleta (sexo, nome, peso, altura, morada, DOB, id_modalidade) VALUES ('M', 'Válter Ferreira Picas Carvalho', '103', '209', 'Santa Lucrécia de Algeriz e Navarra, Braga', '1992-11-9', 5);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-1-4T10-11', 1699, 1);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-4-10T9-47', 1755, 2);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-2-13T13-7', 1471, 3);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-11-23T17-42', 1156, 4);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-12-27T12-4', 1260, 5);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2022-6-8T14-40', 1968, 6);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-10-6T11-51', 64, 7);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2022-9-11T14-37', 104, 8);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-7-5T11-32', 314, 9);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-4-26T16-36', 875, 10);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-12-5T12-48', 1576, 11);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-10-19T11-40', 2042, 12);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2020-10-27T9-33', 1469, 13);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2021-8-10T9-14', 668, 14);
INSERT INTO Prova (data_hora, duração, id_modalidade) VALUES ('2022-8-26T16-34', 1286, 15);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 11, '2019-10-13T12:30', 11, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 12, '2019-04-02T14:15', 11, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2021-11-08T13:30', 86, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2019-05-01T14:00', 86, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2019-08-21T09:00', 86, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2021-06-03T09:30', 2, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 7, '2019-08-14T11:30', 55, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2021-12-14T15:00', 84, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2020-09-18T16:00', 84, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2020-03-01T17:15', 16, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2021-09-27T11:00', 16, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2019-01-31T11:15', 31, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 9, '2021-11-15T11:00', 77, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 6, '2021-07-01T09:45', 44, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 8, '2020-05-22T11:45', 44, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 9, '2021-06-06T15:30', 44, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2020-01-10T17:30', 103, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2020-01-25T17:30', 103, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 12, '2020-12-04T15:30', 5, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 15, '2019-01-09T09:30', 5, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 8, '2021-09-11T15:30', 98, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 7, '2020-04-19T17:30', 15, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2019-06-28T09:00', 15, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 12, '2020-05-21T13:30', 15, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2021-07-06T09:15', 101, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 15, '2019-08-05T14:00', 101, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2020-12-20T12:00', 105, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 6, '2020-05-31T11:15', 105, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2021-11-06T10:45', 105, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2020-01-14T13:30', 35, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2021-09-11T14:15', 35, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 5, '2019-09-05T15:30', 102, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2021-10-26T12:00', 72, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2021-03-22T12:30', 72, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 7, '2019-12-24T12:15', 90, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 12, '2020-02-19T16:15', 90, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 15, '2019-04-06T16:00', 66, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2020-05-09T15:30', 66, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2020-02-10T09:45', 66, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2019-07-13T15:45', 98, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2020-06-27T11:30', 98, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2020-09-05T09:00', 4, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 6, '2020-06-01T10:15', 4, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2020-01-11T09:30', 86, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2019-11-09T15:15', 86, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 7, '2020-09-02T11:15', 86, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2021-12-25T09:00', 62, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2021-12-23T15:15', 62, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 9, '2021-02-03T17:15', 62, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2020-12-23T13:30', 26, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2020-03-25T16:15', 26, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 8, '2019-11-17T09:30', 81, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2021-08-20T12:45', 81, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2019-12-11T11:45', 81, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2020-01-27T10:00', 11, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2021-06-19T16:30', 11, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2021-06-27T10:15', 11, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2021-03-01T14:15', 3, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2019-12-10T15:00', 53, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 15, '2019-07-02T16:30', 53, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 7, '2020-10-28T16:45', 53, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 6, '2020-04-13T10:30', 4, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 14, '2019-01-12T09:15', 4, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 6, '2019-06-15T17:45', 89, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2019-09-28T15:30', 89, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2021-02-27T10:30', 89, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2019-03-30T17:30', 13, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 7, '2020-06-06T17:15', 13, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 12, '2021-11-08T14:00', 23, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2020-01-08T12:30', 81, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 12, '2019-04-12T12:15', 81, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 7, '2020-10-05T15:00', 81, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2021-07-23T11:15', 75, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2021-01-02T09:00', 4, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2021-03-25T11:45', 4, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2021-11-11T12:15', 54, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 7, '2021-04-18T15:00', 54, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 8, '2021-06-04T15:45', 53, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2020-07-08T15:15', 53, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 9, '2020-07-30T10:30', 53, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 9, '2021-01-20T16:15', 68, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 7, '2019-10-11T15:00', 68, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 12, '2019-07-24T15:45', 92, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 12, '2021-08-06T11:30', 92, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2021-05-25T17:00', 53, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 8, '2021-06-25T16:00', 45, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2021-10-11T13:45', 33, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2021-07-02T15:30', 6, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 6, '2021-04-12T11:15', 6, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 15, '2019-01-14T15:45', 79, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 13, '2021-12-22T10:45', 79, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 5, '2019-03-05T12:15', 93, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 14, '2021-03-27T16:30', 93, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 11, '2021-05-23T14:00', 93, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 15, '2020-01-03T13:15', 65, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 1, 13, '2020-01-04T14:15', 40, 1);
INSERT INTO TesteClinico (nome, realizado, preço, data_hora, id_atleta, id_profissional) VALUES ('Controlo Anti-Doping', 0, 10, '2020-01-05T12:45', 50, 1);
